### ISSUE TITLE
citation

### ISSUE THREAD

**Issue by maocenWang** [FY387/Intelligent-segmentation-of-tunnel-lining-cracks#1]
if I want to use this dataset, how should I cite it?

**Comment by FY387** [comment]
Thanks for your interest, and we are glad that you can adopt this dataset for research. The paper is still being typed and proofread. The detailed information of our paper will be uploaded to github in the next 1-2 weeks, so that you can cite it according to the paper format.

**Comment by FY387** [comment]
Author: Yong Feng, Xiao-Lei Zhang, Shi-Jin Feng, Wei Zhang, Kan Hu, Yue-Wu Da
Title: Intelligent segmentation and quantification of tunnel lining cracks via computer vision
Journal: Structural Health Monitoring
Year: 2024
DOI: 10.1177/14759217241254748
ISSN: 1475-9217

**Comment by maocenWang** [comment]
Sorry, I did not find this article. Has he been published or has been sent and received online ? Is it convenient for you to provide a download link for this article ? Thank you very much.

**Comment by FY387** [comment]
There are some delays in the journal's publication process due to a network disruption at Sage. The Sage's global IT experts and supporting teams are diligently working to minimize service interruptions wherever possible. It will take some time to access the article. Thanks.

**Comment by maocenWang** [comment]
你好，关于您在文章中提到的NUAAcrack-2000数据集，相关的参考文献[34]并未提供数据，请问是标记错误吗
